# Generated by Django 3.2.12 on 2022-09-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpet', '0002_auto_20220920_1933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
