# Generated by Django 3.2.12 on 2022-09-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpet', '0005_auto_20220921_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
